### PR TITLE
feat: test case update in helloworld

### PR DESCRIPTION
**Pull request by GroophyLifefor**

### CODE REVIEW

**Comment by GroophyLifefor** [comment]
@ErikSchierboom Can you review?

**Review by ErikSchierboom — APPROVED** [review]

**Comment by GroophyLifefor** [comment]
@ErikSchierboom Okay, so what are we supposed to do now, is that it, are we now going to publish the programming language on the page?

**Comment by GroophyLifefor** [comment]
Waiting for Tuesday for a reply.

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom Okay, so what are we supposed to do now, is that it, are we now going to publish the programming language on the page?

Not yet, there's still things to do before we'll do that. See https://github.com/exercism/batch/issues/1 for an overview. The most important part is to add (at least) 20 exercises.

**Comment by GroophyLifefor** [comment]
> Not yet, there's still things to do before we'll do that. See https://github.com/exercism/batch/issues/1 for an overview. The most important part is to add (at least) 20 exercises.

Ah, this is really going to be a bit of a challenge, 20 exercises won't come out all at once, but I'll try to get them all out.

**Comment by ErikSchierboom** [comment]
> Ah, this is really going to be a bit of a challenge, 20 exercises won't come out all at once, but I'll try to get them all out.

That is perfectly fine, there is no rush. You could always ask for help on the forum.

**Comment by GroophyLifefor** [comment]
> That is perfectly fine, there is no rush. You could always ask for help on the forum.

Thanks you, I'll.

**Pull request merged**
