### PR TITLE
standartilize changes and removed old files

### PR DESCRIPTION
**Pull request by GroophyLifefor**

### CODE REVIEW

**Comment by GroophyLifefor** [comment]
Due to a mistake I made while using Git I opened a wrong pr, the current one is correct and committed but the previous commit is not showing here.

No more parameters are needed and I made it more student friendly.

https://github.com/exercism/batch/blob/6990a6bce401e5831f15b0c2866ceb742290600a/exercises/practice/hello-world/HelloWorldTest.bat#L7-L27

**Comment by ErikSchierboom** [comment]
Not sure what happened, but https://github.com/exercism/batch/pull/4 seems to have been the right PR. Why did you close that?

**Comment by GroophyLifefor** [comment]
@ErikSchierboom your mention pr has old commits too because I forget to merge <kbd>main to initialize</kbd> which behind for main.

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom your mention pr has old commits too because I forget to merge main to initialize which behind for main.

Yes, but that's not a problem because we squash merge anyway. This PR only removes two files, it doesn't add back the right files.

**Comment by GroophyLifefor** [comment]
> Yes, but that's not a problem because we squash merge anyway. This PR only removes two files, it doesn't add back the right files.

I'm not sure what was going on in the background, when I saw so many commits together, I thought I broke something and tried to fix it quickly.

**Comment by ErikSchierboom** [comment]
No problem. Could you either create a new PR with the right changes or update this PR with the correct changes? You can add as many commits as you like, we'll squash them into a single commit when we merge them anyways.

**Comment by GroophyLifefor** [comment]
@ErikSchierboom Isn't everything right now? What do you want me to fix?

**Comment by GroophyLifefor** [comment]
I am not in a rush, but time is passing and we are stuck here, I am waiting for mentoring to move forward in the test-runner part.

**Comment by ErikSchierboom** [comment]
Oh I somehow missed another pr. Sorry! I'll work on the test runner this week

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
