### PR TITLE
new exercise - series

### PR DESCRIPTION
**Pull request by GroophyLifefor**

### CODE REVIEW

**Comment by GroophyLifefor** [comment]
[no important files changed]

**Comment by GroophyLifefor** [comment]
it seems to be triggered because I edited the test file of another exercise, if you look at the changes I edited a simple comment line, there is no problem

**Comment by ErikSchierboom** [comment]
> it seems to be triggered because I edited the test file of another exercise, if you look at the changes I edited a simple comment line, there is no problem

Just to be clear what the above message means. If this PR is merged, the fact that a test file was updated would mean _all_ of its solutions would have to be rerun in the test runner. Whilst the track is currently not yet live, this doesn't yet matter, but it _will_ be important once it is live. The fact that it is "just a comment" is not something we can detect, so we'd have to rerun the solutions. However, you, the maintainer, _can_ identify that it is "just a comment", in which case rerunning the tests wouldn't change any outcome. If this is true, you should add the `[no important files changed]` text **to the commit message** (you can add it when you get the commit text after pressing on Squash and merge).

See https://exercism.org/docs/building/tracks#h-avoiding-triggering-unnecessary-test-runs for more information.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by GroophyLifefor** [comment]
> > it seems to be triggered because I edited the test file of another exercise, if you look at the changes I edited a simple comment line, there is no problem
> 
> Just to be clear what the above message means. If this PR is merged, the fact that a test file was updated would mean _all_ of its solutions would have to be rerun in the test runner. Whilst the track is currently not yet live, this doesn't yet matter, but it _will_ be important once it is live. The fact that it is "just a comment" is not something we can detect, so we'd have to rerun the solutions. However, you, the maintainer, _can_ identify that it is "just a comment", in which case rerunning the tests wouldn't change any outcome. If this is true, you should add the `[no important files changed]` text **to the commit message** (you can add it when you get the commit text after pressing on Squash and merge).
> 
> See https://exercism.org/docs/building/tracks#h-avoiding-triggering-unnecessary-test-runs for more information.

Thanks you so much, I got it.

**Pull request merged**
